# Generated by Django 5.1.3 on 2024-11-23 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalApp', '0002_alter_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=20)),
                ('mobile', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=100)),
                ('profile', models.ImageField(default='', upload_to='profile/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigitalApp.user')),
            ],
        ),
    ]
