# Generated by Django 5.1.3 on 2024-11-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalApp', '0005_alter_userprofile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
