# Generated by Django 5.1.3 on 2024-11-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalApp', '0006_alter_userprofile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('member', 'Member'), ('watchman', 'Watchman'), ('chairman', 'Chairman')], max_length=10),
        ),
    ]
